/**
 * Pure parsing and probing of YouTube's public endpoints.
 *
 * WHY THIS IS SEPARATE FROM `lib/youtube.ts`
 *
 * Two runtimes need this logic. `lib/youtube.ts` runs in Node during
 * `astro build`; `functions/api/videos.ts` runs in the Workers runtime on every
 * cache miss. The Pages Function is bundled by esbuild from the repository
 * root, outside the Astro project, so it cannot resolve the `~/` alias and
 * cannot import anything that reaches for `~/data/*`.
 *
 * This file therefore imports **nothing at all**. That is the constraint that
 * keeps it shareable — adding a single import here is what would force the
 * function to grow its own copy of the parser, the way
 * `scripts/refresh-youtube.mjs` already had to.
 */

/** One entry, reduced to the fields the site actually renders. */
export interface FeedVideo {
  id: string;
  title: string;
  published: string;
  /** Used for VideoObject structured data, which requires a description. */
  description: string;
}

/** Atom escapes these; titles routinely contain apostrophes and ampersands. */
export function decodeEntities(value: string): string {
  return value
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&');
}

/**
 * Extract entries without an XML parser.
 *
 * The feed is machine-generated by YouTube with a stable, flat shape, so
 * targeted regexes are adequate and save a dependency — one that would have to
 * be bundled into the Worker as well. If this ever needs to read nested or
 * attribute-heavy fields, swap in a real parser rather than growing the
 * patterns.
 */
export function parseFeed(xml: string, limit: number): FeedVideo[] {
  const videos: FeedVideo[] = [];

  for (const entry of xml.split('<entry>').slice(1)) {
    const id = entry.match(/<yt:videoId>([^<]+)<\/yt:videoId>/)?.[1];
    const title = entry.match(/<title>([\s\S]*?)<\/title>/)?.[1];
    const published = entry.match(/<published>([^<]+)<\/published>/)?.[1];
    const description = entry.match(/<media:description>([\s\S]*?)<\/media:description>/)?.[1];

    if (!id || !title) continue;

    videos.push({
      id,
      title: decodeEntities(title.trim()),
      published: published ?? '',
      description: description ? decodeEntities(description.trim()).slice(0, 300) : '',
    });

    if (videos.length >= limit) break;
  }

  return videos;
}

/** What an oEmbed probe concluded about a video. */
export type Embeddability = 'embeddable' | 'blocked' | 'gone';

const OEMBED_URL = 'https://www.youtube.com/oembed?format=json&url=';

/**
 * Ask YouTube whether a video may be embedded, before we try.
 *
 * The Atom feed says nothing about this. A video whose owner turned off
 * "Permitir insertar" — the default for live streams started from some
 * clients — still appears in the feed, and the iframe then renders YouTube's
 * own grey *"El propietario del video inhabilitó la reproducción en otros
 * sitios web"* panel inside our layout. The visitor sees a broken tile on our
 * page for a setting on theirs.
 *
 * oEmbed is the only public endpoint that answers this without an API key:
 *
 *   200        embeddable
 *   401 / 403  embedding disabled by the owner
 *   404        deleted, private or otherwise gone
 *
 * Anything else — a timeout, a 429, YouTube having a bad minute — is treated
 * as embeddable. A flaky probe must not silently downgrade every tile on the
 * page to a plain link; the worst case of guessing "yes" is the panel we had
 * before, and the worst case of guessing "no" is that working videos stop
 * playing inline.
 */
async function probeOnce(id: string, fetchImpl: typeof fetch): Promise<Embeddability> {
  const target = encodeURIComponent(`https://www.youtube.com/watch?v=${id}`);

  try {
    const response = await fetchImpl(`${OEMBED_URL}${target}`);

    if (response.status === 404) return 'gone';
    if (response.status === 401 || response.status === 403) return 'blocked';
    return 'embeddable';
  } catch {
    return 'embeddable';
  }
}

/**
 * A verdict only counts against a video if two probes agree.
 *
 * MEASURED, NOT DEFENSIVE
 *
 * Both of the channel's videos answered 401 and then 200 an hour later, from
 * the same machine, with nothing changed in between that we can point to. So a
 * single 401 does not mean "the owner disabled embedding" — it can equally mean
 * "ask again". The same goes for a 404 on a video the feed just listed.
 *
 * The asymmetry is the point. `embeddable` is the state that leaves a tile
 * exactly as it would have been without any of this, so it is returned
 * immediately and costs one request. `blocked` downgrades a working video to a
 * plain link and `gone` removes it from the page entirely — both are visible
 * regressions if wrong, so each is re-checked, and a disagreement resolves to
 * `embeddable` rather than to the worse outcome.
 *
 * The second request only happens on the unhappy path, which is rare.
 */
export async function probeEmbeddable(
  id: string,
  fetchImpl: typeof fetch = fetch,
): Promise<Embeddability> {
  const first = await probeOnce(id, fetchImpl);
  if (first === 'embeddable') return first;

  const second = await probeOnce(id, fetchImpl);
  return second === first ? first : 'embeddable';
}

/** A feed entry once its oEmbed verdict has been applied. */
export interface ProbedVideo extends FeedVideo {
  embeddable: boolean;
}

/**
 * Combine entries with their verdicts: drop what is gone, mark what is blocked.
 *
 * IF EVERY PROBE SAYS "GONE", BELIEVE NONE OF THEM
 *
 * Rate limiting is the failure this whole pipeline is built around, and YouTube
 * signals it with **404** — the same status oEmbed returns for a deleted video.
 * A throttled caller therefore sees the feed 404, falls back to the snapshot,
 * and then watches every single probe 404 as well. Acting on that verdict would
 * empty the videos section, which is exactly the outcome the snapshot exists to
 * prevent; the check would have caused the failure it was added to avoid.
 *
 * So a unanimous "gone" is read as "the probes are not working right now" and
 * discarded entirely — including the embeddability half, since tiles that were
 * playing fine yesterday should not all silently degrade to plain links on a
 * throttled build.
 *
 * A channel really losing every video at once is not a case worth optimising
 * for. Being rate limited demonstrably is.
 */
export function applyVerdicts(videos: FeedVideo[], verdicts: Embeddability[]): ProbedVideo[] {
  const usable = verdicts.some((verdict) => verdict !== 'gone');
  if (!usable) return videos.map((video) => ({ ...video, embeddable: true }));

  return videos
    .map((video, index) => ({ video, verdict: verdicts[index] ?? 'embeddable' }))
    .filter(({ verdict }) => verdict !== 'gone')
    .map(({ video, verdict }) => ({ ...video, embeddable: verdict === 'embeddable' }));
}
