import { YOUTUBE, type FeaturedVideo } from '~/config/site';
import snapshot from '~/data/youtube-feed.json';

/**
 * Build-time fetch of the channel's public YouTube Atom feed.
 *
 * Runs during `astro build`, never in the browser. The result is baked into
 * static HTML, so visitors make no request to YouTube and there is no API key
 * anywhere in the pipeline.
 *
 * Design constraint that shapes this whole file: **a content fetch must never
 * be able to block a deploy.** If YouTube is slow, rate-limiting the build
 * runner, or briefly down, the build has to carry on and ship the manually
 * curated videos instead. Every failure path below returns an empty list
 * rather than throwing.
 */

const FEED_URL = 'https://www.youtube.com/feeds/videos.xml?channel_id=';
const TIMEOUT_MS = 8000;

/** Minimal Atom entry shape. The feed carries far more; we take what we render. */
interface FeedVideo {
  id: string;
  title: string;
  published: string;
}

/**
 * Extract entries without an XML parser.
 *
 * The feed is machine-generated by YouTube with a stable, flat shape, so
 * targeted regexes are adequate and save a dependency. If this ever needs to
 * read nested or attribute-heavy fields, swap in a real parser rather than
 * growing the patterns.
 */
function parseFeed(xml: string, limit: number): FeedVideo[] {
  const videos: FeedVideo[] = [];

  for (const entry of xml.split('<entry>').slice(1)) {
    const id = entry.match(/<yt:videoId>([^<]+)<\/yt:videoId>/)?.[1];
    const title = entry.match(/<title>([\s\S]*?)<\/title>/)?.[1];
    const published = entry.match(/<published>([^<]+)<\/published>/)?.[1];

    if (!id || !title) continue;

    videos.push({ id, title: decodeEntities(title.trim()), published: published ?? '' });
    if (videos.length >= limit) break;
  }

  return videos;
}

/** Atom escapes these; titles routinely contain apostrophes and ampersands. */
function decodeEntities(value: string): string {
  return value
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&');
}

const toFeatured = (video: FeedVideo): FeaturedVideo => ({
  provider: 'youtube',
  id: video.id,
  title: video.title,
});

/**
 * The committed snapshot, used when the live feed is unavailable.
 *
 * Refresh it with `pnpm --filter @qa-ulew/web content:youtube`.
 */
function fromSnapshot(): FeaturedVideo[] {
  return snapshot.videos.slice(0, YOUTUBE.limit).map(toFeatured);
}

/**
 * Latest videos from the configured channel, newest first.
 *
 * Tries the live feed, falls back to the committed snapshot, and never throws.
 *
 * The fallback is not paranoia. YouTube's public feed is rate limited, and when
 * it throttles it answers **404** rather than 429 — indistinguishable from a
 * deleted channel. Observed here: the same channel id served videos and then
 * 404'd from the same machine half an hour later. Cloudflare Pages builds from
 * shared IPs, so they are throttled more often, not less.
 *
 * Without the snapshot, one unlucky build silently deploys an empty videos
 * section. With it, the worst case is videos from the last refresh.
 */
export async function fetchLatestVideos(): Promise<FeaturedVideo[]> {
  if (!YOUTUBE.channelId) return [];

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), TIMEOUT_MS);

  try {
    const response = await fetch(`${FEED_URL}${encodeURIComponent(YOUTUBE.channelId)}`, {
      signal: controller.signal,
      headers: {
        accept: 'application/atom+xml,application/xml',
        // A browser UA measurably reduces how often the feed throttles.
        'user-agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36',
      },
    });

    if (!response.ok) {
      const fallback = fromSnapshot();
      console.warn(
        `[youtube] feed returned ${response.status} (rate limiting answers 404); ` +
          `using snapshot of ${fallback.length} video(s)`,
      );
      return fallback;
    }

    const live = parseFeed(await response.text(), YOUTUBE.limit);
    if (live.length === 0) return fromSnapshot();

    return live.map(toFeatured);
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    const fallback = fromSnapshot();
    console.warn(
      `[youtube] feed unavailable (${reason}); using snapshot of ${fallback.length} video(s)`,
    );
    return fallback;
  } finally {
    clearTimeout(timeout);
  }
}

/**
 * Pinned videos first, then the feed, with duplicates removed.
 *
 * A video pinned in FEATURED_VIDEOS will also appear in the feed; the pinned
 * entry wins so its curated title and position are preserved.
 */
export function mergeVideos(pinned: FeaturedVideo[], feed: FeaturedVideo[]): FeaturedVideo[] {
  const seen = new Set(pinned.map((video) => `${video.provider}:${video.id}`));
  return [...pinned, ...feed.filter((video) => !seen.has(`${video.provider}:${video.id}`))];
}
